name: Build and Deploy to Docker Hub

on:
  push:
    tags:
      - v*

env:
  IMAGE: $(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]' | sed -e 's,docker-,,')
  TAG: ${{ github.ref_name }}
  USER: $(echo ${{ github.repository_owner }} | tr '[A-Z]' '[a-z]')

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  build:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ env.USER }} --password-stdin
 
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMAGE }}:${{ env.TAG }}
          docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
    
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.IMAGE }}:latest
